jobs:
    always-pass:
        runs-on: ubuntu-latest
        steps:
            - id: some_id
              name: Checkout code
              uses: actions/checkout@v4
            - name: Run placeholder script
              run: |
                echo "This is a placeholder script."
                echo "Modify this block to do real work."
            - if: always()
              name: Force success
              run: echo "Marking job as succeeded, regardless of earlier failures."
name: Always Succeed CI
"on":
    push:
        branches:
            - '**'
